Add instruction for creating a none-k8s VM using CAPO
Nordix/airship-clusterapi-docs pull request #37
Opened 2021-02-18 13:33 UTC by Xenwar

2021-02-18 13:33 UTC, Xenwar commented
/assign @kashifest

2021-02-18 13:33 UTC, Xenwar commented
/cc @maelk

2021-02-19 09:12 UTC, kashifest requested changes
A few typos. Otherwise lgtm

2021-02-19 09:12 UTC, kashifest commented on capo/provision_none_k8s_node.md
> +Then we create the ```mMchine``` and ```Openstackmachine``` resources. Note that
Machine

2021-02-19 09:12 UTC, kashifest commented on capo/provision_none_k8s_node.md
> +As descussed above, it is possible to create a VM by using CAPO utilities.
discussed

2021-02-19 09:13 UTC, furkatgofurov7 requested changes
Good job!
Small nits

2021-02-19 09:13 UTC, furkatgofurov7 commented on capo/provision_none_k8s_node.md
> +the ```KubeadmConfig``` in the ```Machine``` resource is already created during provsioning of the cluster.
```suggestion
the ```KubeadmConfig``` in the ```Machine``` resource is already created during provisioning of the cluster.
```

2021-02-19 09:13 UTC, furkatgofurov7 commented on capo/provision_none_k8s_node.md
> +Machine
could be more descriptive

2021-02-19 09:13 UTC, furkatgofurov7 commented on capo/provision_none_k8s_node.md
> +As descussed above, it is possible to create a VM by using CAPO utilities.
```suggestion
As discussed above, it is possible to create a VM by using CAPO utilities.
```

2021-02-19 09:13 UTC, furkatgofurov7 commented on capo/provision_none_k8s_node.md
> +The created machine has the following properies:
```suggestion
The created machine has the following properties:
```

2021-02-19 09:17 UTC, furkatgofurov7 commented on capo/provision_none_k8s_node.md
> +  sshKeyName: xenwar-key
Is this a public key?

2021-02-19 09:20 UTC, furkatgofurov7 commented on capo/provision_none_k8s_node.md
> +  sshKeyName: xenwar-key
Sorry, it is just name, disregard.

2021-02-19 09:34 UTC, smoshiur1237 reviewed
Small nits, otherwise Looks good to me

2021-02-19 09:34 UTC, smoshiur1237 commented on capo/provision_none_k8s_node.md
> +In order to create a VM that is not part of kubernetes cluster using the CAPO controllers, the following resources created.
```suggestion
In order to create a VM that is not part of kubernetes cluster using the CAPO controllers, the following resources are created. 
```

2021-02-19 09:39 UTC, Xenwar commented on capo/provision_none_k8s_node.md
> +  sshKeyName: xenwar-key
replaced

2021-02-19 09:40 UTC, Xenwar commented on capo/provision_none_k8s_node.md
> +In order to create a VM that is not part of kubernetes cluster using the CAPO controllers, the following resources created.
fixed

2021-02-19 09:42 UTC, Xenwar commented on capo/provision_none_k8s_node.md
> +The created machine has the following properies:
fixed

2021-02-19 09:42 UTC, Xenwar commented on capo/provision_none_k8s_node.md
> +As descussed above, it is possible to create a VM by using CAPO utilities.
fixed

2021-02-19 09:42 UTC, Xenwar commented on capo/provision_none_k8s_node.md
> +Machine
changed

2021-02-19 09:42 UTC, Xenwar commented on capo/provision_none_k8s_node.md
> +the ```KubeadmConfig``` in the ```Machine``` resource is already created during provsioning of the cluster.
changed

2021-02-19 09:42 UTC, Xenwar commented on capo/provision_none_k8s_node.md
> +As descussed above, it is possible to create a VM by using CAPO utilities.
fixed

2021-02-19 09:42 UTC, Xenwar commented on capo/provision_none_k8s_node.md
> +Then we create the ```mMchine``` and ```Openstackmachine``` resources. Note that
fixed

2021-02-19 10:07 UTC, fmuyassarov approved these changes
just a single nit, otherwise LGTM

2021-02-19 10:07 UTC, fmuyassarov commented on capo/provision_none_k8s_node.md
> +Then we create the ```Machine``` and ```Openstackmachine``` resources.
```suggestion
Then we create the ```Machine``` and ```OpenstackMachine``` resources.
```

2021-02-22 09:40 UTC, Xenwar commented on capo/provision_none_k8s_node.md
> +Then we create the ```Machine``` and ```Openstackmachine``` resources.
fixed

2021-02-22 09:47 UTC, smoshiur1237 approved these changes

2021-02-22 09:49 UTC, namnx228 approved these changes
LGTM

2021-02-22 09:54 UTC, furkatgofurov7 reviewed
/lgtm

2021-02-22 09:55 UTC, fmuyassarov reviewed
LGTM

2021-02-22 10:18 UTC, furkatgofurov7 approved these changes

2021-02-22 10:52 UTC, kashifest approved these changes

2021-02-22 10:53 UTC, merged