Add development environment set up guide
Nordix/airship-clusterapi-docs pull request #40
Opened 2021-03-02 11:37 UTC by Xenwar

2021-03-02 11:58 UTC, kashifest requested changes

2021-03-02 11:58 UTC, kashifest commented on capo/capo-development-environment.md
> +2. Deploy a workload provision a target cluster
This line is unclear. Need rewriting.

2021-03-02 11:58 UTC, kashifest commented on capo/capo-development-environment.md
> +This gives a single file with multiple objects. It requires some changes as describe below. Creating the resources in the given order could help in understanding the relationship between the objects.
as described

2021-03-02 11:58 UTC, kashifest commented on capo/capo-development-environment.md
> +Also, the ```externalNetworkId``` value may change from time to time. Therefore, you need to update the enviroment variable ```OPENSTACK_EXTERNAL_NETWORK_ID```. The following command could help with
environment

2021-03-02 11:58 UTC, kashifest commented on capo/capo-development-environment.md
> +A floating IP created, but is not attached to any instance. If you do not create the CP node quickly enough,
is created

2021-03-02 11:58 UTC, kashifest commented on capo/capo-development-environment.md
> +- There is no cloud init data specified in the above kcp resource
full stop ?

2021-03-02 11:58 UTC, kashifest commented on capo/capo-development-environment.md
> +Some of them related to the development environment, and some related to CAPO itself.
are related

2021-03-02 11:58 UTC, kashifest commented on capo/capo-development-environment.md
> +With 3 KCP nodes, stopping a nodes that has the floating IP assigned to it will result in the floating IP migrating to the other nodes.
a  node

2021-03-02 11:58 UTC, kashifest commented on capo/capo-development-environment.md
> +With 3 KCP nodes, deleting a node leaves only two nodes. No new node is provisioned to compensate for the missing one. However, as described above, the KCP resources shows 3 nodes.
show 3 nodes

2021-03-02 11:58 UTC, kashifest commented on capo/capo-development-environment.md
> +When scaling up KCP from 1 to 3 nodes, the process succeeds as was discussed ealier. However, the floating IP jumps from node to node for no apparent reason. But, this has no impact when using ```kub
as discussed earlier

2021-03-02 12:02 UTC, namnx228 requested changes
Just some small nits. Otherwise, LGTM.

2021-03-02 12:27 UTC, Xenwar commented on capo/capo-development-environment.md
> +With 3 KCP nodes, stopping a nodes that has the floating IP assigned to it will result in the floating IP migrating to the other nodes.
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +Some of them related to the development environment, and some related to CAPO itself.
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +These variables are used for authenticating against openstack clsuter ```mycloud_default``` (as shown in clouds.yaml file)
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +These environment variables are divided into two. One group is generated using a script while the second group needs to be filled manually.
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +When scaling up KCP from 1 to 3 nodes, the process succeeds as was discussed ealier. However, the floating IP jumps from node to node for no apparent reason. But, this has no impact when using ```kub
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +With 3 KCP nodes, deleting a node leaves only two nodes. No new node is provisioned to compensate for the missing one. However, as described above, the KCP resources shows 3 nodes.
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +With 3 KCP nodes, stopping a nodes that has the floating IP assigned to it will result in the floating IP migrating to the other nodes.
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +Some of them related to the development environment, and some related to CAPO itself.
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +- There is no cloud init data specified in the above kcp resource
added

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +A floating IP created, but is not attached to any instance. If you do not create the CP node quickly enough,
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +Also, the ```externalNetworkId``` value may change from time to time. Therefore, you need to update the enviroment variable ```OPENSTACK_EXTERNAL_NETWORK_ID```. The following command could help with
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +This gives a single file with multiple objects. It requires some changes as describe below. Creating the resources in the given order could help in understanding the relationship between the objects.
fixed

2021-03-02 12:28 UTC, Xenwar commented on capo/capo-development-environment.md
> +2. Deploy a workload provision a target cluster
done

2021-03-03 13:21 UTC, namnx228 commented
LGTM

2021-03-03 13:37 UTC, kashifest commented
/approve

2021-03-03 13:38 UTC, kashifest approved these changes

2021-03-04 07:41 UTC, namnx228 commented
/approve

2021-03-04 07:42 UTC, namnx228 approved these changes

2021-03-04 07:42 UTC, merged